In [1]:
import pandas as pd
import numpy as np

import pymysql                        # for getting data from a SQL database
from sqlalchemy import create_engine  # for establishing the connection and authentication

from getpass import getpass  # To get the password without showing the input

In [3]:
password = getpass()
#

········

In [4]:
connection_string = 'mysql+pymysql://root:'+password+'@localhost/EVsGermany'
engine = create_engine(connection_string)

In [5]:
type(engine)

sqlalchemy.engine.base.Engine

In [6]:
cars_df = pd.read_csv('cars_final.csv')

/var/folders/pf/nfj1603d1fjc2xkhkrlls95m0000gn/T/ipykernel_63353/2494030787.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  cars_df = pd.read_csv('cars_final.csv')

In [7]:
cars_df.head(10)

      brand commercial_name fuel_type  year      month
0  HONDA UK              JA    petrol  2015  Undefined
1  HONDA UK              JA    petrol  2015  Undefined
2  HONDA UK              JA    petrol  2015  Undefined
3  HONDA UK              JA    petrol  2015  Undefined
4  HONDA UK              JA    petrol  2015  Undefined
5  HONDA UK              JA    petrol  2015  Undefined
6   HYUNDAI         UNKNOWN    diesel  2015  Undefined
7   HYUNDAI         UNKNOWN    diesel  2015  Undefined
8   HYUNDAI         UNKNOWN    diesel  2015  Undefined
9   HYUNDAI         UNKNOWN    petrol  2015  Undefined

In [8]:
charging_df = pd.read_csv('charging_final.csv')

In [9]:
charging_df.head(10)

,operator,type_of_charging_equipment,number_of_charging_points,connected_load,plug_types_1,p1_kw,district_city,city,zip_code,street,house_number,date_of_commissioning,latitude,longitude,avg_kW,month,year
0,GGEW AG,Standard_charger,1,4.6,AC Socket Type 2,4.6,Landkreis Bergstraße,Lorsch,64653,Klosterstr.,23,2017-01-02,49.653064,8.572109,4.6,1,2017
1,Pfalzwerke AG,Super_charger,2,75.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Lorsch,64653,Nibelungenstraße,135-137,2021-04-27,49.652969,8.554764,37.5,4,2021
2,ENTEGA Energie GmbH,Standard_charger,2,44.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Fürth,64658,Krumbacher Str.,39,2017-11-21,49.658037,8.787881,22.0,11,2017
3,Entega Plus GmbH,Standard_charger,2,22.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Fürth,64658,Erbacher Str.,102,2022-04-08,49.663670,8.796830,11.0,4,2022
4,Entega Plus GmbH,Standard_charger,2,22.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Fürth,64658,Schulstr.,12,2022-04-08,49.646360,8.781410,11.0,4,2022
5,Vogel Autohäuser GmbH & Co. KG,Standard_charger,2,44.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Zwingenberg,64673,Gießer Weg,16,2019-11-24,49.722681,8.602622,22.0,11,2019
6,Entega Plus GmbH,Super_charger,2,150.0,DC Coupler Combo,150.0,Landkreis Bergstraße,Einhausen,64683,In der Wolfshecke,1,2022-07-20,49.663796,8.543574,75.0,7,2022
7,Entega Plus GmbH,Standard_charger,2,22.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Einhausen,64683,Friedensstr.,3,2022-09-15,49.671588,8.548023,11.0,9,2022
8,ALDI SÜD,Standard_charger,2,44.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Lautertal,64686,Nibelungenstraße,349-351,2021-02-16,49.711272,8.703318,22.0,2,2021
9,ENTEGA Energie GmbH,Standard_charger,2,44.0,AC Socket Type 2,22.0,Landkreis Bergstraße,Grasellenbach,64689,Am Kurpark,1,2017-07-31,49.627596,8.858623,22.0,7,2017

In [10]:
charging_df.to_sql('charging_infrastructure', engine, if_exists='replace', index=False)

36254

In [11]:
cars_df.to_sql('cars_germany', engine, if_exists='replace', index=False)

15048854